[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "product classificator"
version = "0.0.2"
description = "Classification of products using ruCLIP embeddings of product description and image"
authors = [{name="Sergei Sakhonenkov", email="sergei.sakhonenkov@gmail.com"}]
license = "MIT"
readme = "README.md"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools]
packages = ["product_classificator"]
package-dir = {"product_classificator" = "product_classificator"}
package-data = {"product_classificator.heads" = ["*.pt", "*.pkl"]}

