[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"


setup(
    name='product_classificator',
    version=get_version(),
    author='Sergei Sakhonenkov',
    author_email='sergei.sakhonenkov@gmail.com',
    description='Classification of products using ruCLIP embeddings of product description and image',
    packages=['product_classificator'],
    package_dir={'product_classificator': 'product_classificator'},
    package_data={'product_classificator.heads': ['*.pt', '*.pkl']},
    include_package_data=True,
    long_description=readme(),
    long_description_content_type='text/markdown',
    install_requires=get_requirements(),
)