[tool.poetry]
name = "product-classificator"
version = "0.0.2"
description = "Classification of products using ruCLIP embeddings of product description and image"
authors = ["SergeiSakh <sergei.sakhonenkov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
youtokentome = "^1.0.6"
stocaching = "^0.2.0"
torchvision = "^0.18.0"
nltk = "^3.8.1"
pillow = "^10.2.0"
matplotlib = "^3.9.0"
tqdm = "^4.66.0"
scikit-learn = "^1.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
